### ISSUE TITLE
Can you make this a separate tool from the main biotracker

### ISSUE THREAD

**Issue by Edzero** [Tuesday1028/GTFO_MapperTracker#1]
Hi,

Unsure how to contact your directly sorry.
Can you create a new biotracker tool with a new name?
I'd like to have the old biotracker, plus the mappertracker as different options.

That way I can allow old biotracker on early levels in a rundown, then allow mappertracker on later levels.
Thanks

**Comment by Tuesday1028** [comment]
I can consider customizing one for you.

**Comment by Tuesday1028** [comment]
[Hikaria.MapperTracker_with_IgnoredPublicGearNames.zip](https://github.com/Tuesday1028/GTFO_MapperTracker/files/14912140/Hikaria.MapperTracker_with_IgnoredPublicGearNames.zip)

Config: Settings/IgnoredPublicGearNames.json

Take a look and see if there are any issues with doing it this way, or feel free to offer any other suggestions.
